baseURL = "https://tablesparalleles.fr/"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "Tables Parallèles"
enableRobotsTXT = true
disableHugoGeneratorInject = true
timeZone = "Europe/Paris"

[params]
  giscusRepoId = "R_kgDOUB67qw"
  giscusCategoryId = "DIC_kwDOUB67q84DECvu"
  description = "Carnets d'un MJ qui mène plusieurs mondes de front."
  tagline = "Carnets d'un MJ qui mène plusieurs mondes de front"
  buttondown = "tablesparalleles"

[taxonomies]
  serie = "serie"

[permalinks]
  posts = "/:year/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML", "RSS"]

[pagination]
  pagerSize = 10

[markup.tableOfContents]
  startLevel = 2
  endLevel = 2
